name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-20"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTk3MjFlYzQtZDU0MC00OTRiLWI0NTktNThiMzJmMDU3NjRlIiwidGVuYW50X2lkIjoiMTgxNDAxMTM1MmQyYTgzZjAzMmQ1NjRiZDNjMWNiMWNlY2FkNTUzYzNjMTQxNTE0NzhlMThmYzg3NDdhZTg0ZCIsImludGVybmFsX3NlY3JldCI6IjFhZmQ4YTIxLWRhZjItNDgzYS05ZjE3LTBhZWVjZTAyNmJmNiJ9.ep87pAr08Fw_aP33hT0xYUV8rDRoMuNLUVr6BnjiqW4"
JWT_SECRET="fam"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1